// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SimJobShop")>]
[<assembly: AssemblyProductAttribute("SimJobShop")>]
[<assembly: AssemblyDescriptionAttribute("Discrete event simulation of a flexible job shop")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SimJobShop"
    let [<Literal>] AssemblyProduct = "SimJobShop"
    let [<Literal>] AssemblyDescription = "Discrete event simulation of a flexible job shop"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
