// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SimJobShop")>]
[<assembly: AssemblyProductAttribute("SimJobShop")>]
[<assembly: AssemblyDescriptionAttribute("Discrete event simulation of a flexible job shop")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SimJobShop"
    let [<Literal>] AssemblyProduct = "SimJobShop"
    let [<Literal>] AssemblyDescription = "Discrete event simulation of a flexible job shop"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
